package vn.cloud.cardservice.model;

import jakarta.annotation.Nullable;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.*;
import org.hibernate.annotations.TimeZoneStorage;
import org.hibernate.annotations.TimeZoneStorageType;
import org.springframework.format.annotation.DateTimeFormat;
import vn.cloud.cardservice.validator.NoFunnyNames;

import java.time.LocalTime;

@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper=true) //include attributes from superclass in the equals and hashcode methods
@Entity
@Inheritance(strategy=InheritanceType.JOINED)
public class BusinessUser extends BaseUserModel
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE) // prevent manually setting of Id using lombok, all Id must be generated by the database to maintain integrity
    @Column(unique=true)
	private Long id;

    @NoFunnyNames
    @NotBlank
    @Column(nullable=false)
    private String businessName;

    @NoFunnyNames
    @NotBlank
    @Column(nullable=false)
    private String branch;

    @NotBlank
    @Column(nullable=false)
    private String businessType;

    @NotBlank
    @Column(nullable=false)
    private String address;

    @NotBlank
    @Column(nullable=false)
    private String postalCode;

    @Nullable
    @Pattern(regexp="^\\+[0-9]+[0-9]+") //country code and phone number
    private String contactNumber;

    @NotBlank
    @Column(nullable=false)
    private String openingDays;
    @TimeZoneStorage(TimeZoneStorageType.COLUMN)
    @DateTimeFormat(iso = DateTimeFormat.ISO.TIME)
    private LocalTime openingTime;
    @TimeZoneStorage(TimeZoneStorageType.COLUMN)
    @DateTimeFormat(iso = DateTimeFormat.ISO.TIME)
    private LocalTime closingTime;


}

