package vn.cloud.cardservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;


@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
public class FoodWasteItem implements Serializable
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE) // prevent manually setting of Id using lombok, all Id must be generated by the database to maintain integrity
    @Column(unique=true)
	private Long id;

    private String name;

    private String category;

    private Integer period;

    private String manufacturer;

    private Double weight;

    @JsonProperty("business")
    @ManyToOne
    private BusinessUser businessUser;



}
